export const ACTION_LABEL: Record<string, string> = {
  DOCUMENT_CREATED: 'Dokumen didaftarkan',
  DOCUMENT_UPDATED: 'Metadata diubah',
  DOCUMENT_ARCHIVED: 'Diarsipkan',
  DOCUMENT_SUPERSEDED: 'Digantikan versi baru',
  DOCUMENT_VERSION_LINKED: 'Ditautkan sebagai versi baru',
  DOCUMENT_VIEWED: 'Dilihat',
  DOCUMENT_OPENED: 'Dibuka',
  DOCUMENT_DOWNLOADED: 'Diunduh',
  ACCESS_DENIED: 'Akses ditolak',
  PERMISSION_CHANGED: 'Izin diubah',
  SECURITY_LEVEL_CHANGED: 'Level keamanan diubah',
  DOCUMENT_CONFIRMED: 'Draft dikonfirmasi',
  DOCUMENT_REJECTED: 'Draft ditolak',
  DOCUMENT_SOURCE_MISSING: 'File sumber hilang',
  APPROVAL_REQUESTED: 'Permintaan akses diajukan',
  ACCESS_APPROVED: 'Permintaan akses disetujui',
  ACCESS_REJECTED: 'Permintaan akses ditolak',
  ACCESS_EXPIRED: 'Akses sementara berakhir',
  OWNER_APPROVAL_FLAG_CHANGED: 'Tanda wajib persetujuan Owner diubah',
}

export const FIELD_LABEL: Record<string, string> = {
  documentName: 'Nama',
  documentNumber: 'Nomor',
  categoryId: 'Kategori',
  divisionId: 'Divisi',
  picUserId: 'PIC',
  externalUrl: 'Tautan Drive',
  effectiveDate: 'Tgl berlaku',
  expiryDate: 'Tgl kedaluwarsa',
  confirmedSummary: 'Ringkasan',
}
